user_new:
    path:   /new
    defaults: { _controller: "AppBundle:User:new"}
    methods: POST

user_edit:
    path:   /edit
    defaults: { _controller: "AppBundle:User:edit"}
    methods: POST

user_upload_avatar:
    path:   /upload-avatar
    defaults: { _controller: "AppBundle:User:uploadAvatar"}
    methods: POST

video_channel:
    path:   /channel/{user_id}
    defaults: { _controller: "AppBundle:User:channel", user_id: null }
    methods: GET