video_new:
    path:   /new
    defaults: { _controller: "AppBundle:Video:new"}
    methods: POST

video_edit:
    path:   /edit/{video_id}
    defaults: { _controller: "AppBundle:Video:edit", video_id: null}
    methods: POST

video_upload:
    path:   /upload/{video_id}
    defaults: { _controller: "AppBundle:Video:upload", video_id: null}
    methods: POST
